/* Model routing is managed internally by the server. */
(()=>{
 const openChatBase=setChatOpen;setChatOpen=function(open,mode){if(open&&(!chatOpen||mode))CreditReview.setMode(mode||'chat');return openChatBase(open);};
 const attachments=new Map();let uploading=false;const list=()=>attachments.get(currentChatKey())||[];
 const picker=document.createElement('input');picker.type='file';picker.accept='.docx,.pptx,.hwp,.hwpx,.gif,.bmp,.tif,.tiff,.xlsx,.xls,.pdf,.json,.txt,.csv,.md,.png,.jpg,.jpeg,.webp';picker.multiple=true;picker.hidden=true;document.body.append(picker);
 const add=document.createElement('button');add.type='button';add.id='chatAttach';add.textContent='+';add.title='대화 파일 첨부 (문서·엑셀·PDF·텍스트·이미지)';add.setAttribute('aria-label','대화 파일 첨부');add.style.cssText='border:0;background:transparent;color:#72836a;font-size:23px;padding:0 5px;line-height:24px';document.querySelector('.compose-options .demo').replaceWith(add);
 const chips=document.createElement('div');chips.id='chatAttachments';chips.style.cssText='display:flex;flex-wrap:wrap;gap:6px;font-size:12px';$('form').prepend(chips);
 function paint(){chips.replaceChildren();for(const item of list()){const tag=document.createElement('span');tag.textContent=item.name+' ';if(item.preview){const img=document.createElement('img');img.src=item.preview;img.alt=item.name;img.style.cssText='width:48px;height:48px;object-fit:contain;vertical-align:middle;margin-right:5px;border-radius:4px';tag.prepend(img);}const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',item.name+' 첨부 제거');remove.onclick=()=>{attachments.set(currentChatKey(),list().filter(x=>x.id!==item.id));paint();};tag.append(remove);chips.append(tag);}add.disabled=uploading;CreditReview.refreshChatFiles();}
 add.onclick=()=>picker.click();async function upload(files){if(uploading){notify('현재 파일 업로드가 끝난 뒤 다시 첨부해 주세요.');return;}const key=currentChatKey();if(files.length+list().length>5){notify('대화 파일은 최대 5개까지 첨부할 수 있습니다.');return;}uploading=true;add.disabled=true;try{for(const file of files){if(file.size>20*1024*1024)throw Error('대화 파일은 한 개당 20MB까지 첨부할 수 있습니다.');const r=await CreditReview.uploadChatFile(file);const rows=attachments.get(key)||[];if(!rows.some(x=>x.id===r.document_id))rows.push({id:r.document_id,name:file.name,preview:file.type.startsWith('image/')?URL.createObjectURL(file):null});attachments.set(key,rows);}notify('대화 파일을 첨부했습니다. 질문을 입력해 주세요.');}catch(e){notify(e.message);}finally{uploading=false;paint();}}
 picker.onchange=()=>{const files=[...picker.files];picker.value='';upload(files);};
 function paste(e){const files=[...(e.clipboardData?.items||[])].filter(x=>x.kind==='file'&&x.type.startsWith('image/')).map(x=>x.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();upload(files);}}
 $('prompt').addEventListener('paste',paste);
 window.CreditReviewChatAttachments={upload,paste,current:()=>{if(uploading)throw Error('파일 업로드가 완료된 뒤 다시 보내주세요.');return list().map(x=>({id:x.id,name:x.name}));},open:()=>picker.click(),remove:index=>{attachments.set(currentChatKey(),list().filter((_,i)=>i!==index));paint();},names:()=>list().map(x=>x.name)};
 const originalChat=renderChat;renderChat=()=>{originalChat();paint();};
 const modeTitle=document.querySelector('.chat-panel-head > span');
 const modeSwitch=document.createElement('button');modeSwitch.type='button';modeSwitch.className='chat-mode-switch';modeSwitch.setAttribute('role','switch');modeSwitch.innerHTML='<span>대화</span><span>의견보완</span>';modeTitle.replaceChildren(modeSwitch);
 function updateMode(){const on=CreditReview.getMode()==='revise';modeSwitch.setAttribute('aria-checked',String(on));modeSwitch.setAttribute('aria-label','의견보완 모드');$('prompt').placeholder=on?'보완할 문장을 선택하고 수정 내용을 입력하세요.':'자유롭게 질문하세요. 문장을 선택하면 함께 참고합니다.';}
 modeSwitch.onclick=()=>CreditReview.setMode(CreditReview.getMode()==='chat'?'revise':'chat');window.addEventListener('credit-review:mode',updateMode);updateMode();
 const modeCSS=document.createElement('style');modeCSS.textContent='.chat-mode-switch{position:relative;display:inline-flex!important;border:1px solid #dbe3d7!important;border-radius:18px!important;background:#edf1e9!important;padding:3px!important;font-size:11px!important;color:#73816d!important;gap:0!important}.chat-mode-switch span{position:relative;padding:4px 9px;z-index:1;white-space:nowrap}.chat-mode-switch:before{content:"";position:absolute;left:3px;top:3px;bottom:3px;width:calc(50% - 3px);border-radius:14px;background:#fff;box-shadow:0 1px 4px #22332215;transition:transform .18s}.chat-mode-switch[aria-checked=true]:before{transform:translateX(100%);background:#d5e4d2}.chat-mode-switch{width:132px!important;min-width:132px!important;flex-shrink:0!important}.chat-mode-switch span{display:block!important;flex:0 0 62px!important;width:62px!important;box-sizing:border-box;text-align:center;font-size:11px!important;font-weight:400!important;color:inherit!important}';document.head.append(modeCSS);
 window.CreditReviewModeCSS=modeCSS.textContent;
 $('reviseToggle').hidden=true;
 const hideChat=$('chatClose');hideChat.replaceChildren(document.createTextNode('숨기기'));hideChat.classList.remove('icon');hideChat.type='button';hideChat.title='숨기기';hideChat.setAttribute('aria-label','숨기기');hideChat.style.cssText='width:auto;height:auto;flex-shrink:0;padding:4px 6px;background:transparent;border:0;font-size:12px;color:#72836a;white-space:nowrap';
 $('prompt').placeholder='자유롭게 질문하세요. 문장을 선택하면 함께 참고합니다.';
 const transparency=document.querySelector('.chat-transparency'),toggle=document.createElement('button');toggle.type='button';toggle.id='chatTransparencyToggle';toggle.textContent='투명도';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','chatTransparencyControls');toggle.style.cssText='padding:4px 6px;background:transparent;border:0;font-size:12px;color:#72836a';
 const controls=document.createElement('span');controls.id='chatTransparencyControls';controls.hidden=true;controls.append($('chatTransparency'),$('chatTransparencyValue'));transparency.replaceWith(toggle);toggle.after(controls);
 toggle.onclick=()=>{controls.hidden=!controls.hidden;toggle.setAttribute('aria-expanded',String(!controls.hidden));if(!controls.hidden)$('chatTransparency').focus();};
 controls.addEventListener('keydown',e=>{if(e.key==='Escape'){controls.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.focus();e.stopPropagation();}});
 const layout=document.createElement('style');layout.textContent='.chat-panel-head{position:relative;justify-content:flex-start;gap:8px}.chat-panel-head>span:first-child{flex:1}#chatTransparencyToggle{margin-left:auto;margin-right:8px}#chatTransparencyControls:not([hidden]){position:absolute;right:90px;top:100%;z-index:10;display:flex;align-items:center;gap:8px;padding:9px 12px;border:1px solid #dce4d8;border-radius:8px;background:#fff;box-shadow:0 3px 10px #25392118;font-size:12px}#chatTransparencyControls input{width:100px}';document.head.append(layout);
 const css=document.createElement('style');css.textContent='.chat-context{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;line-height:1.5}.chat-streaming{white-space:pre-wrap;line-height:1.7}.chat-thinking{padding:10px 4px;color:#82917c;font-size:12px;animation:chat-thinking-pulse 1.4s ease-in-out infinite}@keyframes chat-thinking-pulse{50%{opacity:.45}}@media(prefers-reduced-motion:reduce){.chat-thinking{animation:none}}';document.head.append(css);
})();
