/* The assessment opens only after a history entry is selected. */
(() => {
 const make=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const css=make('style');css.textContent=`
 #reviewHome{position:absolute;inset:29px 0 0;z-index:110;background:#fff;overflow:auto;padding:20px 24px 32px;color:#263c32;font-family:inherit}
 #reviewHome[hidden],#reviewHomeBack[hidden]{display:none!important}
 #reviewHome main{max-width:470px;margin:0 auto}#reviewHome .home-brand{font-size:13px;color:#758478;margin-bottom:24px}
 #reviewHome h1{font-size:21px;margin:0 0 14px}#reviewHome p{color:#758478;font-size:14px;line-height:1.7}
 #reviewHome h2{font-size:17px;margin:34px 0 12px}#reviewHome button{font:inherit;cursor:pointer}
 #reviewHome .home-new{background:#456b54;color:white;border:0;border-radius:8px;padding:13px 22px;margin-top:18px}
 #reviewHome ul{list-style:none;padding:0;margin:0}#reviewHome li{border-bottom:1px solid #e5eae3}#reviewHome .home-case{width:100%;display:flex;align-items:center;justify-content:space-between;text-align:left;background:transparent;border:0;border-radius:0;padding:16px 0;margin:0;color:inherit;gap:16px;text-decoration:none;font-size:13px}
 #reviewHome .home-case:hover{background:#f5f8f3}#reviewHome small{display:block;color:#78867b;margin-top:8px;font-size:12px}
 #reviewHomeBack{position:absolute;bottom:12px;right:16px;z-index:130;border:1px solid #d6dfd5;border-radius:7px;background:#f9fcf8;color:#526957;padding:7px 12px;cursor:pointer}
 #reviewHome main[hidden]{display:none}#reviewHome .entry-back{background:none;border:0;padding:0;color:#718271;margin-bottom:28px}
 #reviewHome form label{display:block;font-size:13px;margin:24px 0 8px}#reviewHome form input{display:block;box-sizing:border-box;width:100%;border:1px solid #d7e0d3;border-radius:6px;padding:12px;font:inherit;color:inherit;background:white}
 #reviewHome form input:focus{outline:2px solid #8aa38d;outline-offset:1px}#reviewHome .entry-error{color:#ad4949;font-size:12px}
 #reviewHome .home-main{height:100%;min-height:0;display:flex;flex-direction:column}#reviewHome .home-main>h1,#reviewHome .home-main>p,#reviewHome .home-main>h2,#reviewHome .home-new,#assessmentSearch{flex-shrink:0}#reviewHome .home-new{align-self:flex-start}#assessmentSearch{box-sizing:border-box;width:100%;padding:10px 12px;border:1px solid #d9e2d5;border-radius:6px;font:inherit;font-size:12px;background:white;color:inherit;margin:0 0 10px}#assessmentHistory{flex:1;min-height:80px;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;padding-right:5px!important}#reviewHome .home-main>h2{margin-top:26px}.home-confirm{position:fixed;inset:auto;margin:0;box-sizing:border-box;width:244px;max-width:calc(100vw - 16px);border:1px solid #d9e2d5;border-radius:8px;padding:14px;color:#354b3c;background:white;font-size:12px;box-shadow:0 5px 18px #233c2220}.home-confirm p{font-size:12px;line-height:1.6;margin:0;white-space:nowrap}.home-confirm::backdrop{background:transparent}.home-confirm>div{display:flex;justify-content:flex-end;gap:7px;margin-top:13px}.home-confirm button{font:inherit;font-size:11px;padding:5px 12px;border:0;border-radius:5px;background:#eef3e9;cursor:pointer}.home-confirm button:last-child{background:#456b54;color:white}
 #reviewHome{padding:36px 20px 30px;background:linear-gradient(180deg,#f7faf6 0,#fff 210px);box-sizing:border-box}
 #reviewHome .home-main>h1{font-size:21px;letter-spacing:-.5px;margin:0 0 7px;font-weight:650}#reviewHome .home-main>p{font-size:12px;line-height:1.65;margin:0;color:#7b887c}
 #reviewHome .home-main>.home-new{width:auto;align-self:flex-end;display:flex;align-items:center;justify-content:center;gap:8px;padding:6px 10px;margin-top:4px;margin-bottom:8px;border-radius:5px;font-size:11px;background:#42664f;box-shadow:0 3px 8px #304a3510}#reviewHome .home-new>span{font-size:14px;line-height:1}#reviewHome .home-new:hover{background:#355841}
 #reviewHome .history-heading{display:flex;align-items:center;gap:7px;margin:15px 0 8px;flex-shrink:0}#reviewHome .history-heading h2{font-size:14px;font-weight:600;margin:0}#reviewHome .history-count{font-size:11px;color:#788774;background:#edf2e9;border-radius:12px;padding:2px 7px}
 #reviewHome .history-search{position:relative;margin-bottom:8px;flex-shrink:0}#reviewHome .history-search>span{position:absolute;left:12px;top:7px;font-size:23px;color:#899585;pointer-events:none}#assessmentSearch{padding:11px 12px 11px 35px;margin:0;background:#fff;border-color:#dde5d9;border-radius:7px;font-size:12px}#assessmentSearch:focus{outline:2px solid #9cb39a;outline-offset:1px}
 #reviewHome .home-case{padding:18px 2px;gap:10px}#reviewHome .history-company{min-width:0;flex:1}#reviewHome .history-company strong{display:block;font-size:13px;font-weight:600;overflow-wrap:anywhere}#reviewHome .history-company small{font-size:11px;color:#899285;margin-top:5px}#reviewHome .history-amount{font-size:12px;color:#5e715e;text-align:right;max-width:48%;overflow-wrap:anywhere;font-variant-numeric:tabular-nums}#reviewHome .history-arrow{font-size:17px;color:#94a28e}#assessmentHistory>li:only-child:not(:has(a)){font-size:12px;color:#8a9687;text-align:center;padding:30px 0;border:0}#reviewHome a:focus-visible{outline:2px solid #9cb39a;outline-offset:-2px}
 #assessmentHistory>li:has(.home-case){display:flex;align-items:center;gap:8px}#assessmentHistory .home-case{min-width:0;flex:1}#reviewHome .history-delete{flex:0 0 24px;width:24px;height:28px;padding:0;border:0;background:transparent;color:#8b9687;font-size:18px;cursor:pointer}#reviewHome .history-delete:hover{color:#a15149}#reviewHome .history-delete:focus-visible{outline:1px solid #9cae97;border-radius:4px}.history-delete-confirm{inset:0;margin:auto;height:fit-content}.history-delete-confirm p{white-space:normal;overflow-wrap:anywhere}
 #reviewHome .history-sorting{display:flex;align-items:center;justify-content:flex-end;gap:5px;flex-shrink:0;margin:0 0 0 auto;font-size:11px;color:#879380}#reviewHome .history-sorting>span{margin-right:5px}#reviewHome .history-sorting button{font-size:11px;padding:5px 6px;border:0;background:transparent;color:#879380;border-radius:5px}#reviewHome .history-sorting button[aria-pressed=true]{background:#edf3e9;color:#45664d;font-weight:600}
 @media(min-width:760px){.app.expanded #reviewHome{padding:clamp(36px,5vh,64px) clamp(32px,6vw,100px) 36px}.app.expanded #reviewHome .home-main{width:100%;max-width:960px}.app.expanded #reviewHome .history-search{width:100%}.app.expanded #assessmentSearch{font-size:14px;padding:14px 16px 14px 40px}.app.expanded #reviewHome .history-search>span{top:10px;left:14px}.app.expanded #reviewHome .history-heading{margin-top:24px;margin-bottom:12px}.app.expanded #reviewHome .history-heading h2{font-size:16px}.app.expanded #reviewHome .history-sorting button{font-size:12px;padding:6px 10px}.app.expanded #reviewHome .home-case{padding:21px 8px;gap:24px}.app.expanded #reviewHome .history-company strong{font-size:15px}.app.expanded #reviewHome .history-company small{font-size:12px}.app.expanded #reviewHome .history-amount{font-size:14px;min-width:180px}.app.expanded #reviewHome .home-main>.home-new{font-size:12px;padding:8px 14px}.app.expanded #reviewHome main:not(.home-main){max-width:480px;width:100%}}
 #reviewHome .manual-entry{max-width:380px}#reviewHome .manual-entry .entry-back{font-size:12px;margin-bottom:18px}#reviewHome .manual-entry h1{font-size:17px;margin:0 0 8px}#reviewHome .manual-entry form label{font-size:12px;margin:16px 0 6px}#reviewHome .manual-entry form input{font-size:13px;padding:9px 10px;border-radius:5px;min-height:36px}#reviewHome .manual-entry .entry-error:empty{display:none}#reviewHome .manual-entry .home-new{display:block;margin:18px 0 0 auto;padding:7px 16px;font-size:12px;border-radius:5px}.app.expanded #reviewHome main.manual-entry{max-width:380px}
 #reviewHome{--field-height:36px;--field-font:12px;--field-radius:6px;--field-border:#d9e2d5}
 #reviewHome #assessmentSearch,#reviewHome .manual-entry form input{box-sizing:border-box;height:var(--field-height);min-height:var(--field-height);font-size:var(--field-font);line-height:18px;border:1px solid var(--field-border);border-radius:var(--field-radius);background:#fff;color:#354b3c;padding-top:8px;padding-bottom:8px}
 #reviewHome .manual-entry form label{font-size:12px;line-height:18px;color:#71816c}#reviewHome .manual-entry h1,#reviewHome .history-heading h2{font-size:14px;font-weight:600;line-height:21px}
 #reviewHome #assessmentSearch:focus,#reviewHome .manual-entry form input:focus{outline:2px solid #9cb39a;outline-offset:1px}
 #reviewHome .home-main>.home-new,#reviewHome .manual-entry .home-new{min-height:28px;padding:6px 10px;font-size:11px;line-height:16px;border-radius:5px;background:#42664f;color:#fff}
 #reviewHome .history-search>span{top:4px}#reviewHome .manual-entry .entry-back{font-size:12px;line-height:18px}
 @media(min-width:760px){.app.expanded #reviewHome{--field-height:40px;--field-font:13px}.app.expanded #reviewHome .history-search>span{top:6px}.app.expanded #reviewHome .history-heading h2,.app.expanded #reviewHome .manual-entry h1{font-size:15px}.app.expanded #reviewHome .home-main>.home-new,.app.expanded #reviewHome .manual-entry .home-new{font-size:12px;padding:7px 12px;min-height:30px}}
 #reviewHome .home-case{display:grid;grid-template-columns:minmax(0,1fr) auto 10px;column-gap:10px;row-gap:8px}#reviewHome .history-amount{max-width:none}#reviewHome .history-dates{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:4px 14px;color:#899285;font-size:10px;line-height:1.5}#reviewHome .history-dates span{white-space:nowrap}@media(min-width:760px){.app.expanded #reviewHome .history-dates{font-size:11px;gap:20px}}
 #reviewHome .history-edit{flex:0 0 24px;width:24px;height:28px;padding:0;border:0;background:transparent;color:#81917b;font-size:17px;cursor:pointer}#reviewHome .history-edit:hover{color:#42664f}#reviewHome .history-edit:focus-visible{outline:1px solid #9cae97;border-radius:4px}
 #reviewHome .history-heading{border-bottom:1px solid #bccbbb;padding-bottom:10px;margin-bottom:0}#assessmentHistory{padding-right:0!important}
 #assessmentHistory>li:has(.home-case){gap:2px}#reviewHome .home-case{grid-template-columns:minmax(0,1fr) 72px 67px;gap:6px;padding:13px 0;min-height:43px;box-sizing:border-box;font-size:11px}#reviewHome .history-company{display:flex;align-items:center;gap:5px;min-width:0}#reviewHome .history-company strong{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;flex:1}#reviewHome .history-company small{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:40%;margin:0}#reviewHome .history-amount{min-width:0;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#reviewHome .history-dates{grid-column:auto;display:block;font-size:10px;white-space:nowrap;text-align:right;overflow:hidden;text-overflow:ellipsis}#reviewHome .history-edit,#reviewHome .history-delete{flex-basis:20px;width:20px;font-size:16px}
 @media(min-width:760px){.app.expanded #reviewHome .home-case{grid-template-columns:minmax(0,1fr) 160px 100px;gap:20px;padding:15px 8px}.app.expanded #reviewHome .history-company strong{font-size:14px}.app.expanded #reviewHome .history-company small{font-size:12px}.app.expanded #reviewHome .history-amount{min-width:0;font-size:13px}.app.expanded #reviewHome .history-dates{font-size:12px}}
 #reviewHome .history-heading{border-bottom:0;padding-bottom:0;margin-bottom:10px}#reviewHome .history-columns{display:grid;grid-template-columns:minmax(0,1fr) 60px 72px 67px 42px;gap:6px;align-items:center;padding:0 0 9px;border-bottom:1px solid #bccbbb;font-size:10px;color:#7e8b79;flex-shrink:0}#reviewHome .history-columns span:nth-child(n+3){text-align:right}#reviewHome .history-columns span:last-child{text-align:center}#reviewHome .home-case{grid-template-columns:minmax(0,1fr) 60px 72px 67px}#reviewHome .history-company{display:contents}#reviewHome .history-company small{max-width:none}#assessmentHistory>li:has(.home-case){gap:2px}#assessmentHistory .home-case{margin-right:4px}
 @media(min-width:760px){.app.expanded #reviewHome .history-columns{grid-template-columns:minmax(0,1fr) 150px 160px 100px 42px;gap:20px;font-size:12px;padding-left:8px;padding-right:0}.app.expanded #reviewHome .home-case{grid-template-columns:minmax(0,1fr) 150px 160px 100px;gap:20px;padding-right:0}.app.expanded #assessmentHistory .home-case{margin-right:18px}}
 `;document.head.append(css);
 const home=make('section');home.id='reviewHome';home.setAttribute('aria-label','메인화면');
 const main=make('main');main.className='home-main';main.setAttribute('aria-label','심사의견 생성 대상 여신 선택');
 const start=make('button','수기등록');start.className='home-new';const historyHead=make('div');historyHead.className='history-heading';const count=make('span');count.className='history-count';historyHead.append(make('h2','여신 등록내역'),count);start.prepend(make('span','＋'));
 const search=make('input');search.type='search';search.id='assessmentSearch';search.placeholder='업체명 또는 여신신청번호 검색';search.setAttribute('aria-label','여신 등록내역 검색');const searchBox=make('div');searchBox.className='history-search';const searchIcon=make('span','⌕');searchIcon.setAttribute('aria-hidden','true');searchBox.append(searchIcon,search);main.append(searchBox,start);
 const sorting=make('div');sorting.className='history-sorting';sorting.setAttribute('role','group');sorting.setAttribute('aria-label','정렬조건');let sortBy='date',sortDirection=-1;const sortButtons=[];for(const [key,text] of [['name','이름순'],['date','등록일순']]){const button=make('button',text);button.type='button';button.setAttribute('aria-pressed',String(key===sortBy));if(key===sortBy)button.textContent=text+' ↓';button.onclick=()=>{if(sortBy===key)sortDirection*=-1;else{sortBy=key;sortDirection=key==='name'?1:-1;}sortButtons.forEach(([k,b,label])=>{b.setAttribute('aria-pressed',String(k===sortBy));b.textContent=label+(k===sortBy?(sortDirection===1?' ↑':' ↓'):'');});render();};sortButtons.push([key,button,text]);sorting.append(button);}historyHead.append(sorting);main.append(historyHead);const columns=make('div');columns.className='history-columns';columns.setAttribute('aria-hidden','true');for(const name of ['업체명','신청번호','신청금액','등록일자','관리'])columns.append(make('span',name));main.append(columns);
 const list=make('ul');list.id='assessmentHistory';list.setAttribute('aria-label','여신 등록내역');main.append(list);search.addEventListener('input',render);home.append(main);appWindow.append(home);
 const back=make('button','메인화면');back.id='reviewHomeBack';back.hidden=true;
 function displayAmount(raw){const won=BigInt(raw);const [unit,label,places]=won>=100000000n?[100000000n,'억원',8]:won>=1000000n?[1000000n,'백만원',6]:won>=10000n?[10000n,'만원',4]:[1n,'원',0];const fraction=places?(won%unit).toString().padStart(places,'0').replace(/0+$/,''):'';return (won/unit).toLocaleString('ko-KR')+(fraction?'.'+fraction:'')+label;}
 function assessmentInfo(c){const raw=String(c.applicationAmount??'');return '여신신청번호: '+(c.applicationNumber||'미입력')+' · 신청금액: '+(/^\d+$/.test(raw)?displayAmount(raw):'미입력');}
 function historyDate(value){const date=new Date(Number(value));return value&&Number.isFinite(date.getTime())?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date).replace(/\. /g,'.').replace(/\.$/,''):'기록 없음';}
 function render(){list.replaceChildren();companies.map((c,i)=>({c,i})).sort((a,b)=>sortDirection*(sortBy==='name'?(a.c.name.localeCompare(b.c.name,'ko')||a.i-b.i):((Number(a.c.registeredAt)||0)-(Number(b.c.registeredAt)||0)||a.i-b.i))).forEach(({c,i})=>{if(c.hiddenFromHistory||c.name==='업체 미선택'||!(c.name+' '+(c.applicationNumber||'')).toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase()))return;const item=make('li'),row=make('a');row.href='#assessment';row.className='home-case';const label=make('div');label.className='history-company';label.append(make('strong',c.name),make('small',c.applicationNumber||'미등록'));const right=make('div');right.className='history-amount';const raw=String(c.applicationAmount??'');right.append(make('span',/^\d+$/.test(raw)?displayAmount(raw):'금액 미등록'));row.title=assessmentInfo(c);const arrow=make('span','›');arrow.className='history-arrow';row.append(label,right);label.querySelector('small').title=c.applicationNumber?'신청번호 '+c.applicationNumber:'신청번호 미등록';const dates=make('div');dates.className='history-dates';dates.title='등록일자 '+historyDate(c.registeredAt);dates.append(make('span',historyDate(c.registeredAt)));row.append(dates);row.onclick=e=>{e.preventDefault();selectCompany(i);if(currentCompany===i){c.lastUsedAt=Date.now();home.hidden=true;back.hidden=false;CreditReview.saveLocal().catch(()=>notify('이용일자를 저장하지 못했습니다.'));}};const remove=make('button','×');remove.type='button';remove.className='history-delete';remove.title='목록에서 삭제';remove.setAttribute('aria-label',c.name+' 평가이력 목록에서 삭제');remove.onclick=()=>askDelete(c);const editButton=make('button','✎');editButton.type='button';editButton.className='history-edit';editButton.title='등록정보 수정';editButton.setAttribute('aria-label',c.name+' 등록정보 수정');editButton.onclick=()=>openEdit(c);item.append(row,editButton,remove);list.append(item);});count.textContent=String(list.children.length)+'건';if(!list.children.length)list.append(make('li',search.value.trim()?'검색 결과가 없습니다.':'여신 등록내역이 없습니다.'));}
 const deleteDialog=make('dialog');deleteDialog.className='home-confirm history-delete-confirm';deleteDialog.setAttribute('aria-label','평가이력 삭제 확인');const deleteText=make('p'),deleteActions=make('div'),cancelDelete=make('button','아니요'),confirmDelete=make('button','삭제');cancelDelete.type=confirmDelete.type='button';deleteActions.append(cancelDelete,confirmDelete);deleteDialog.append(deleteText,deleteActions);appWindow.append(deleteDialog);let deletionTarget=null;
 function askDelete(company){deletionTarget=company;deleteText.textContent=company.name+' 등록 정보를 삭제하시겠습니까?';deleteDialog.showModal();}
 cancelDelete.onclick=()=>deleteDialog.close();deleteDialog.addEventListener('close',()=>{deletionTarget=null;});
 confirmDelete.onclick=async()=>{const company=deletionTarget;if(!company)return;confirmDelete.disabled=true;company.hiddenFromHistory=true;try{await CreditReview.saveLocal();deleteDialog.close();render();}catch(e){delete company.hiddenFromHistory;notify('목록 삭제를 저장하지 못했습니다. 다시 시도해 주세요.');}finally{confirmDelete.disabled=false;}};
 let editTarget=null;
 const entry=make('main');entry.className='manual-entry';entry.hidden=true;home.append(entry);
 const entryBack=make('button','‹ 돌아가기');entryBack.type='button';entryBack.className='entry-back';entry.append(entryBack,make('h1','수기등록'));
 const form=make('form');entry.append(form);
 function field(id,title,max){const label=make('label',title),input=make('input');label.htmlFor=id;input.id=id;input.name=id;input.required=true;input.maxLength=max;form.append(label,input);return input;}
 const companyName=field('newCompanyName','업체명',80),applicationNumber=field('newApplicationNumber','여신신청번호',80),amount=field('newApplicationAmount','신청금액 (원)',21);
 amount.inputMode='numeric';amount.placeholder='원 단위로 입력';
 amount.addEventListener('input',()=>{amount.setCustomValidity('');const digits=amount.value.replace(/,/g,'');if(/^\d*$/.test(digits))amount.value=digits.replace(/\B(?=(\d{3})+(?!\d))/g,',');});
 const error=make('p');error.className='entry-error';error.setAttribute('role','alert');const submit=make('button','등록');submit.type='submit';submit.className='home-new';form.append(error,submit);
 function showMain(){entry.hidden=true;main.hidden=false;home.setAttribute('aria-label','메인화면');render();home.hidden=false;back.hidden=true;}
 entryBack.onclick=showMain;
 back.onclick=()=>{if(editing||revisionBusy){notify('진행 중인 수정을 먼저 완료해 주세요.');return;}closePanels();showMain();};
 start.onclick=()=>{if(editTarget){form.reset();editTarget=null;}entry.querySelector('h1').textContent='수기등록';submit.textContent='등록';amount.setCustomValidity('');closePanels();home.hidden=false;back.hidden=true;main.hidden=true;entry.hidden=false;home.setAttribute('aria-label','여신정보 입력');error.textContent='';companyName.focus();};
 function openEdit(c){editTarget=c;entry.querySelector('h1').textContent='등록정보 수정';submit.textContent='저장';companyName.value=c.name;applicationNumber.value=c.applicationNumber||'';const raw=String(c.applicationAmount??'');amount.value=/^\d+$/.test(raw)?BigInt(raw).toLocaleString('ko-KR'):'';amount.setCustomValidity('');error.textContent='';main.hidden=true;entry.hidden=false;home.hidden=false;home.setAttribute('aria-label','등록정보 수정');companyName.focus();}
 form.onsubmit=async e=>{e.preventDefault();error.textContent='';const name=companyName.value.trim(),number=applicationNumber.value.trim(),value=amount.value.replace(/,/g,'');
  if(!name||!number){error.textContent='업체명과 여신신청번호를 입력해 주세요.';return;}
  if(!/^\d+$/.test(value)||BigInt(value)<=0n){amount.setCustomValidity('신청금액은 0보다 큰 원 단위 정수로 입력해 주세요.');amount.reportValidity();return;}
  if(companies.some(c=>c!==editTarget&&!c.hiddenFromHistory&&c.applicationNumber===number)){error.textContent='이미 등록된 여신신청번호입니다. 여신 등록내역에서 확인해 주세요.';return;}
  if(editing||revisionBusy){error.textContent='진행 중인 수정을 먼저 완료해 주세요.';return;}
  const digits=BigInt(value).toString(),formatted=displayAmount(digits);
  if(editTarget){
   const target=editTarget,previous={name:target.name,registrationName:target.registrationName,applicationNumber:target.applicationNumber,applicationAmount:target.applicationAmount,applicationCurrency:target.applicationCurrency,caseInfo:target.caseInfo};
   Object.assign(target,{name,registrationName:name,applicationNumber:number,applicationAmount:digits,applicationCurrency:'KRW',caseInfo:number+' · '+formatted});submit.disabled=true;
   try{await CreditReview.saveLocal();if(companies[currentCompany]===target){$('companyName').textContent=name;$('companyName').title=name;CreditReview.refreshChatFiles();}editTarget=null;form.reset();showMain();}
   catch(e){Object.assign(target,previous);error.textContent='저장하지 못했습니다. 다시 시도해 주세요.';}finally{submit.disabled=false;}return;
  }
  companies.push({id:crypto.randomUUID(),registeredAt:Date.now(),lastUsedAt:Date.now(),name,applicationNumber:number,applicationAmount:digits,applicationCurrency:'KRW',caseInfo:number+' · '+formatted,example:false,state:emptyCompanyState()});
  selectCompany(companies.length-1);if(currentCompany!==companies.length-1){companies.pop();error.textContent='진행 중인 작업을 먼저 완료해 주세요.';return;}
  home.hidden=true;back.hidden=false;form.reset();entry.hidden=true;main.hidden=false;render();
  try{await CreditReview.saveLocal();}catch(e){notify('저장에 실패했습니다. 창을 닫기 전에 다시 확인해 주세요.');}
 };
 renderCompanyForm=()=>start.onclick();
 const confirmHome=make('dialog');confirmHome.className='home-confirm';confirmHome.setAttribute('aria-label','메인화면 이동 확인');confirmHome.append(make('p','메인화면으로 이동하시겠습니까?'));
 const actions=make('div'),no=make('button','아니요'),yes=make('button','네');no.type=yes.type='button';actions.append(no,yes);confirmHome.append(actions);appWindow.append(confirmHome);
 no.onclick=()=>confirmHome.close();yes.onclick=async()=>{try{await CreditReview.saveLocal();}catch(e){notify('저장에 실패해 이동하지 않았습니다.');return;}confirmHome.close();closePanels();showMain();};
 function askHome(anchor){if(editing||revisionBusy){notify('진행 중인 수정을 먼저 완료해 주세요.');return;}const rect=anchor&&Number.isFinite(anchor.left)?anchor:$('rail_companies').getBoundingClientRect();if(!confirmHome.open)confirmHome.showModal();const box=confirmHome.getBoundingClientRect();confirmHome.style.left=Math.max(8,Math.min(rect.left,innerWidth-box.width-8))+'px';confirmHome.style.top=Math.max(8,Math.min(rect.bottom+7,innerHeight-box.height-8))+'px';}
 window.addEventListener('resize',()=>{if(confirmHome.open)confirmHome.close();});
 renderCompanies=askHome;
 $('rail_companies').onclick=e=>{e.preventDefault();e.stopImmediatePropagation();askHome();};
 CreditReview.frame.openCompanies=askHome;
 const load=CreditReview.loadCase;CreditReview.loadCase=async(...args)=>{const result=await load(...args);render();return result;};
 CreditReview.ready.then(render);
})();
